const ERROR_RAISED = 'ERROR_RAISED';
const ERROR_DISMISSED = 'ERROR_DISMISSED';
const ERROR_DISMISSED_AND_NAVIGATED = 'ERROR_DISMISSED_AND_NAVIGATED';

export { ERROR_RAISED, ERROR_DISMISSED, ERROR_DISMISSED_AND_NAVIGATED };
